@productId=
PUT http://localhost:5000/api/products/{{productId}} HTTP/1.1
content-type: application/json

{
  "name": "Sample Product",
  "description": "This is a sample product description.",
  "price": 29.99,
  "image": "http://example.com/sample-product.jpg"
}